Feat: Client App Template
Tutorfi/Tutorfi pull request #118
Opened 2024-06-09 22:16 UTC by RuikangRPI

- simple solidjs template in docker
- configured dockerfile for client commands to start up app
- configured docker compose for client app
- see port 3000 after compose
- documentation for frontend development in README.md in client folder

Container composes and works.

2024-06-10 11:41 UTC, jason490 requested changes
Besides those two comments I made it looks good

2024-06-10 11:41 UTC, jason490 commented on client/compose.yaml
I don't think we need this file because the docker compose file is in the deployments section

2024-06-10 11:41 UTC, jason490 commented on client/vite.config.js
> +})
In here you should create a proxy to the backend ip and port. In docker, instead of specifying an ip, you use the container name as the ip, so in our case "app:8000"

2024-06-10 11:41 UTC, jason490 commented on SETUP.md
Do u want to put this in the wiki?

2024-06-10 12:17 UTC, RuikangRPI commented on client/compose.yaml
Removed and app works

2024-06-10 13:30 UTC, RuikangRPI commented on SETUP.md
Moved to wiki.

2024-06-10 15:46 UTC, RuikangRPI commented on client/vite.config.js
> +})
changes made, container composes, no way to check for working proxy

2024-06-11 01:49 UTC, jason490 requested changes
Just a few minor configs changes for the proxy and it should be good

2024-06-11 01:49 UTC, jason490 commented on client/vite.config.js
> +    port: 3000,
```suggestion
    port: 3000,
    watch: {
        usePolling: true
    },
```
This allows for autoreload of the frontend inside WSL2 for "windows" users who are editing the files outside of the WSL2 VM.
Check usePolling in https://vitejs.dev/config/server-options#server-watch

2024-06-11 01:49 UTC, jason490 commented on client/vite.config.js
> +        target: 'http://app:8000',
```suggestion
        target: 'http://app:8000',
        changeOrigin: true,
        secure: false,
```
Just make sure to have changeOrigin to true. I believe it has to do with the client denying any request, since its going through the vite server then to the api and back.
https://vitejs.dev/config/server-options#server-proxy
Also, have secure to false, it makes things less weird

2024-06-11 17:51 UTC, RuikangRPI commented on client/vite.config.js
> +    port: 3000,
done

2024-06-11 17:51 UTC, RuikangRPI commented on client/vite.config.js
> +        target: 'http://app:8000',
done

2024-06-11 19:15 UTC, jason490 approved these changes

2024-06-11 19:15 UTC, merged