23 account testing
Tutorfi/Tutorfi pull request #59
Opened 2024-02-23 21:38 UTC by bnavac

### What is the current behavior?
We do not have a way to test the code we have. Nor do we have a way to tests the test we write on docker.

### What is the new behavior?
We can create docker containers locally and in github actions.

### Other information?

No

go test ./...

2024-02-23 23:43 UTC, jason490 requested changes
Finish linting the added go files and other failing tests

2024-03-21 19:47 UTC, jason490 requested changes
Looks good, but I left a few comments

2024-03-21 19:47 UTC, jason490 commented on app/internal/handlers/account/account.go
> +		return utils.RenderComponents(c, 200, logintempl.Error(err.Error()), nil)
It seems like this was merged incorrectly because if the person put an invalid regex name then the form would no longer show. Instead it would show the error and the user would have retype all their credentials.

2024-03-21 19:47 UTC, jason490 commented on app/internal/handlers/account/account_test.go
> +		"あいうえお@example.com",
Should this be an invalid email?

2024-03-21 19:47 UTC, jason490 commented on app/internal/handlers/account/account_test.go
> +		t.Logf("Dummy")
Change this to a more easily understandable log

2024-03-21 19:47 UTC, jason490 commented on app/internal/handlers/account/account_test.go
> +	//t.Logf("Email test completed")
Should this stay?

2024-03-21 19:47 UTC, jason490 commented on app/internal/storage/postgres/error.go
> +	sqlError error //idk the format of sql errors, so leaving this here in case we need to access the raw error
You should remove the first part of the sentence in the comment

2024-03-22 18:31 UTC, bnavac commented on app/internal/handlers/account/account_test.go
> +		"あいうえお@example.com",
According to the source I found it on.

2024-03-24 00:08 UTC, jason490 approved these changes

2024-03-24 00:09 UTC, merged